database:
  image: mysql
  container_name: mysql-dev
  command: mysqld --user=root --verbose
  volumes:
   - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "dogs"
    MYSQL_USER: "user"
    MYSQL_PASSWORD: "user"
    MYSQL_ROOT_PASSWORD: "root"